version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: msclientes
      POSTGRES_USER: Harolito
      POSTGRES_PASSWORD: 1234
      TZ: America/Guayaquil
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - red-ms
    restart: always

  ms-clientes:
    image: harolitodocker/ms-clientes:latest
    container_name: ms-clientes
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/msclientes
      SPRING_DATASOURCE_USERNAME: Harolito
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
    networks:
      - red-ms
    restart: always

volumes:
  db_data:

networks:
  red-ms:
